import { Channel } from '@/types/iptv';

export function createIptvPlayerHtml(channel: Channel): string {
  const url = JSON.stringify(channel.url);
  const userAgent = JSON.stringify(channel.userAgent || '');
  const referer = JSON.stringify(channel.referer || '');
    const drm = JSON.stringify(channel.drm);
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"><style>
*{box-sizing:border-box}html,body,#stage{margin:0;width:100%;height:100%;overflow:hidden;background:#000}video{width:100%;height:100%;object-fit:contain;background:#000}button{border:0;color:#fff;background:none}#loading,#error{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:14px;color:#fff;font:14px sans-serif;text-align:center;padding:24px;background:#000;z-index:4}#error{display:none;color:#ffd2d2}#error button{padding:11px 18px;border-radius:8px;background:#0284c7;font-weight:700}#controls{position:absolute;inset:0;display:none;z-index:3}#controls.show{display:block}.center{position:absolute;top:50%;left:0;right:0;display:flex;justify-content:center;align-items:center;gap:34px;transform:translateY(-50%)}.round{width:60px;height:60px;border-radius:50%;background:#fff;color:#222;font-size:26px}.skip{font-size:16px;font-weight:800}.skip small{display:block;font-size:9px;color:#ddd;margin-top:2px}.bottom{position:absolute;bottom:0;left:0;right:0;padding:12px 22px 14px;background:rgba(0,0,0,.68)}.track{height:4px;border-radius:3px;background:#777;overflow:hidden}.value{height:100%;width:0;background:#fff}.times{display:flex;justify-content:space-between;color:#ddd;font:10px sans-serif;margin-top:5px}.actions{display:flex;align-items:center;margin-top:7px}.actions button{font-size:22px;padding:5px 9px}.spacer{flex:1}.live{font:bold 10px sans-serif;background:rgba(255,255,255,.15);border-radius:5px;padding:5px 8px}
  </style></head><body><div id="stage"><video id="video" autoplay playsinline webkit-playsinline></video><div id="loading">Đang kết nối đến kênh...</div><div id="error"><span id="errorText"></span><button onclick="location.reload()">Thử lại</button></div><div id="controls"><div class="center"><button class="skip" id="back">5<small>lùi</small></button><button class="round" id="play">▶</button><button class="skip" id="forward">15<small>tới</small></button></div><div class="bottom"><div class="track"><div class="value" id="value"></div></div><div class="times"><span id="current">LIVE</span><span id="duration">LIVE</span></div><div class="actions"><button id="playSmall">▶</button><button id="mute">🔊</button><span class="spacer"></span><span class="live">LIVE</span><button id="fullscreen">⛶</button></div></div></div></div>
<style>.quality-menu{display:none;position:absolute;right:28px;bottom:72px;width:190px;padding:9px;border:1px solid rgba(255,255,255,.16);border-radius:9px;background:rgba(18,18,22,.97);box-shadow:0 8px 30px rgba(0,0,0,.5);color:#fff;font:12px sans-serif}.quality-menu.show{display:block}.quality-heading{padding:5px 8px 8px;color:#aaa;font-size:11px}.quality-option{display:flex;align-items:center;justify-content:space-between;width:100%;padding:9px 8px;border-radius:6px;text-align:left}.quality-option.active{background:rgba(255,255,255,.12)}.quality-check{color:#4ade80;font-weight:800}.quality-button{font-size:11px!important;font-weight:800;border:1px solid rgba(255,255,255,.65);border-radius:4px;padding:4px 6px!important;min-width:38px!important}</style></head><body><div id="stage"><video id="video" autoplay playsinline webkit-playsinline></video><div id="loading">Đang kết nối đến kênh...</div><div id="error"><span id="errorText"></span><button onclick="location.reload()">Thử lại</button></div><div id="controls"><div class="center"><button class="skip" id="back">5<small>lùi</small></button><button class="round" id="play">▶</button><button class="skip" id="forward">15<small>tới</small></button></div><div id="qualityMenu" class="quality-menu"><div id="qualityOptions"></div></div><div class="bottom"><div class="track"><div class="value" id="value"></div></div><div class="times"><span id="current">LIVE</span><span id="duration">LIVE</span></div><div class="actions"><button id="playSmall">▶</button><button id="mute">🔊</button><span class="spacer"></span><button id="quality" class="quality-button">HD</button><span class="live">LIVE</span><button id="fullscreen">⛶</button></div></div></div></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.11.2/shaka-player.compiled.js"></script><script src="https://cdn.jsdelivr.net/npm/hls.js@1.5.13/dist/hls.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mpegts.js@1.7.3/dist/mpegts.js"></script><script>
const v=document.getElementById('video'),loading=document.getElementById('loading'),errorBox=document.getElementById('error'),errorText=document.getElementById('errorText'),controls=document.getElementById('controls'),play=document.getElementById('play'),playSmall=document.getElementById('playSmall'),mute=document.getElementById('mute'),current=document.getElementById('current'),duration=document.getElementById('duration'),value=document.getElementById('value'),quality=document.getElementById('quality'),qualityMenu=document.getElementById('qualityMenu'),qualityOptions=document.getElementById('qualityOptions');
const url=${url},ua=${userAgent},ref=${referer},drm=${drm};let timer,hlsInstance=null;
function send(type,msg){try{window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify({type,msg}))}catch(e){}}
function ready(){loading.style.display='none';send('ready')};function fail(msg){loading.style.display='none';errorText.textContent=msg;errorBox.style.display='flex';send('error',msg)}
function show(){controls.classList.add('show');send('controls_visibility','true');clearTimeout(timer);timer=setTimeout(()=>{if(!v.paused){controls.classList.remove('show');qualityMenu.classList.remove('show');send('controls_visibility','false')}},3500)}
function icon(){const text=v.paused?'▶':'❚❚';play.textContent=text;playSmall.textContent=text}
function toggle(){if(v.paused)v.play().catch(()=>{});else v.pause();icon();show()};function fmt(x){if(!Number.isFinite(x)||x<=0)return'LIVE';const n=Math.floor(x);return Math.floor(n/60).toString().padStart(2,'0')+':'+(n%60).toString().padStart(2,'0')}
function b64hex(x){try{const raw=atob(x.replace(/-/g,'+').replace(/_/g,'/'));return Array.from(raw).map(c=>c.charCodeAt(0).toString(16).padStart(2,'0')).join('')}catch(e){return x}}
function keyOf(x){try{if(!x)return null;if(x.trim()[0]==='{'){const k=JSON.parse(x).keys[0];return{kid:b64hex(k.kid),key:b64hex(k.k)}}const p=x.split(':');return p.length===2?{kid:p[0].trim(),key:p[1].trim()}:null}catch(e){return null}}
function xhr(x){if(ua)try{x.setRequestHeader('User-Agent',ua)}catch(e){}if(ref)try{x.setRequestHeader('Referer',ref)}catch(e){}}
function shaka(){if(!window.shaka||!shaka.Player.isBrowserSupported())return fail('Thiết bị không hỗ trợ DRM');const p=new shaka.Player();p.attach(v);p.getNetworkingEngine().registerRequestFilter((t,r)=>{if(ua)r.headers['User-Agent']=ua;if(ref)r.headers.Referer=ref});const k=keyOf(drm&&drm.licenseKey);if(k){const keys={};keys[k.kid]=k.key;p.configure({drm:{clearKeys:keys}})}p.addEventListener('error',e=>fail('Lỗi DRM'));p.load(url).then(()=>v.play().then(ready).catch(ready)).catch(e=>fail('Không thể tải DRM'))}
function qualityLabel(level){return level.height?level.height+'p':(level.bitrate?Math.round(level.bitrate/1000)+'k':'Auto')}
function renderQuality(){qualityOptions.innerHTML='<div class="quality-heading">Chất lượng hình ảnh</div>';if(!hlsInstance||!hlsInstance.levels.length){qualityOptions.innerHTML+='<div class="quality-heading">Kênh không cung cấp nhiều mức</div>';return}const auto=document.createElement('button');auto.className='quality-option'+(hlsInstance.autoLevelEnabled?' active':'');auto.innerHTML='<span>Tự động</span><span class="quality-check">'+(hlsInstance.autoLevelEnabled?'✓':'')+'</span>';auto.onclick=()=>{hlsInstance.currentLevel=-1;renderQuality();show()};qualityOptions.appendChild(auto);hlsInstance.levels.slice().reverse().forEach((level,index)=>{const actual=hlsInstance.levels.length-1-index;const option=document.createElement('button');option.className='quality-option'+(hlsInstance.currentLevel===actual?' active':'');option.innerHTML='<span>'+qualityLabel(level)+'</span><span class="quality-check">'+(hlsInstance.currentLevel===actual?'✓':'')+'</span>';option.onclick=()=>{hlsInstance.currentLevel=actual;renderQuality();show()};qualityOptions.appendChild(option)})}
function hls(){if(window.Hls&&Hls.isSupported()){hlsInstance=new Hls({enableWorker:true,xhrSetup:xhr});hlsInstance.on(Hls.Events.ERROR,(e,d)=>{if(d.fatal)fail('Lỗi HLS')});hlsInstance.on(Hls.Events.MANIFEST_PARSED,()=>{renderQuality();v.play().then(ready).catch(ready)});hlsInstance.loadSource(url);hlsInstance.attachMedia(v)}else if(v.canPlayType('application/vnd.apple.mpegurl')){quality.disabled=true;v.src=url;v.addEventListener('loadedmetadata',()=>v.play().then(ready).catch(ready))}else fail('Thiết bị không hỗ trợ HLS')}
function transport(type){if(!window.mpegts||!mpegts.isSupported())return fail('Thiết bị không hỗ trợ '+type);const p=mpegts.createPlayer({type,isLive:true,url});p.attachMediaElement(v);p.on(mpegts.Events.ERROR,()=>fail('Lỗi phát '+type));p.load();p.play().then(ready).catch(ready)}
document.getElementById('play').onclick=toggle;document.getElementById('playSmall').onclick=toggle;document.getElementById('mute').onclick=()=>{v.muted=!v.muted;mute.textContent=v.muted?'🔇':'🔊';show()};document.getElementById('quality').onclick=()=>{qualityMenu.classList.toggle('show');show()};document.getElementById('back').onclick=()=>{if(Number.isFinite(v.duration))v.currentTime=Math.max(0,v.currentTime-5);show()};document.getElementById('forward').onclick=()=>{if(Number.isFinite(v.duration))v.currentTime=Math.min(v.duration,v.currentTime+15);show()};document.getElementById('fullscreen').onclick=()=>send('fullscreen_toggle');document.getElementById('stage').onclick=e=>{if(e.target===v){if(controls.classList.contains('show'))controls.classList.remove('show');else show()}};v.onplay=()=>{icon();ready()};v.onpause=icon;v.ontimeupdate=()=>{current.textContent=fmt(v.currentTime);duration.textContent=fmt(v.duration);value.style.width=Number.isFinite(v.duration)&&v.duration>0?(v.currentTime/v.duration*100)+'%':'0%'};
try{const lower=url.toLowerCase();if((drm&&drm.manifestType==='mpd')||lower.includes('.mpd'))shaka();else if((drm&&drm.manifestType==='m3u8')||lower.includes('.m3u8'))hls();else if(lower.includes('.flv'))transport('flv');else if(lower.includes('.ts'))transport('mpegts');else{v.src=url;v.play().then(ready).catch(()=>fail('Không thể phát kênh'))}}catch(e){fail('Lỗi khởi tạo player')}
</script></body></html>`;
}
